### ISSUE TITLE
[주간학습 6/12~6/19]

### ISSUE THREAD

**Issue by spolice0324** [spolice0324/shoveling#81]
## 📌 ToDo

- [ ] 행렬의 곱셈연습문제 | Lv. 2 | 14,597명 | 62%
- [ ] 1차] 캐시2018 KAKAO BLIND RECRUITMENT | Lv. 2 | 15,105명 | 62%
- [ ] 의상해시 | Lv. 2 | 44,979명 | 62%
- [ ]  튜플2019 카카오 개발자 겨울 인턴십 | Lv. 2 | 17,511명 | 62%
- [ ] 기능개발스택/큐 | Lv. 2 | 50,063명 | 61%
- [ ] 할인 행사연습문제 | Lv. 2 | 4,587명 | 61%
- [ ]  프로세스스택/큐 | Lv. 2 | 40,327명 | 61%
- [ ] [1차] 뉴스 클러스터링2018 KAKAO BLIND RECRUITMENT | Lv. 2 | 15,573명 | 60%
- [ ]  피로도완전탐색 | Lv. 2 | 11,695명 | 59%
- [ ]  타겟 넘버깊이/너비 우선 탐색(DFS/BFS) | Lv. 2 | 42,723명 | 59%
- [ ]  k진수에서 소수 개수 구하기2022 KAKAO BLIND RECRUITMENT | Lv. 2 | 10,446명 | 59%
- [ ]  [3차] 압축2018 KAKAO BLIND RECRUITMENT | Lv. 2 | 9,536명 | 58%
- [ ] [3차] n진수 게임2018 KAKAO BLIND RECRUITMENT | Lv. 2 | 9,657명 | 57%
- [ ]  주차 요금 계산2022 KAKAO BLIND RECRUITMENT | Lv. 2 | 11,036명 | 57%
- [ ] 오픈채팅방2019 KAKAO BLIND RECRUITMENT | Lv. 2 | 27,538명 | 57%
- [ ]  땅따먹기연습문제 | Lv. 2 | 11,316명 | 56%
- [ ] 게임 맵 최단거리깊이/너비 우선 탐색(DFS/BFS) | Lv. 2 | 15,742명 | 56%
- [ ]  방문 길이Summer/Winter Coding(~2018) | Lv. 2 | 9,457명 | 56%
- [ ]  스킬트리Summer/Winter Coding(~2018) | Lv. 2 | 19,834명 | 56%

## 📌 ETC
-
